// Auto-generated by scripts/fetch-buildings.mjs
// id -> { lat, lng, name }
export const BUILDINGS: Record<string, { lat: number; lng: number; name: string }> = {
  `osm-way-42706834`: { lat: 33.776274, lng: -84.388219, name: `Scheller College of Business` },
  `osm-way-42792936`: { lat: 33.775714, lng: -84.388512, name: `Crum and Forster Building` },
  `osm-way-179047236`: { lat: 33.776349, lng: -84.388404, name: `Barnes & Noble Bookstore @ Georgia Tech` },
  `osm-way-714119667`: { lat: 33.775500, lng: -84.387888, name: `CODA` },
  `osm-way-791413998`: { lat: 33.775720, lng: -84.387986, name: `High Performance Computing Center` },
};
