name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'
      - 'README.md'
      - 'wrangler.toml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm i -g wrangler@3

      - name: Deploy Worker
        working-directory: worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          wrangler deploy

  migrate:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm i -g wrangler@3

      - name: Apply D1 migrations (idempotent)
        working-directory: worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          set -e
          for f in migrations/0001_init.sql migrations/0002_auth_vibes.sql migrations/0003_presence.sql migrations/0004_vibes_unique.sql migrations/0005_hits_unique.sql; do
            echo "Applying $f"
            # Some ALTER statements may fail if already applied; ignore non-zero and continue
            wrangler d1 execute buzzpulse_db --file ./$f || true
          done

